# Generated by Django 5.1.2 on 2024-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0005_blogpostmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewersprofilemodel",
            name="preferred_content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("articles", "Articles"),
                    ("videos", "Videos"),
                    ("podcasts", "Both"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
